### ISSUE TITLE
Failing Schema Compare Test - VerifySchemaCompareServiceCalls

### ISSUE THREAD

**Issue by lewis-sanchez** [microsoft/sqltoolsservice#1557]
The VerifySchemaCompareServiceCalls integration test is failing.

Error Message:
```
Differences should be null after cancel
Expected: True
But was:  False
```

Stack Trace:
```
at Microsoft.SqlTools.ServiceLayer.IntegrationTests.SchemaCompare.SchemaCompareServiceTests.ValidateScResult(SchemaCompareResult diffResult, DiffEntry& diffEntry, String operationId, Boolean& cancelled) in /mnt/vss/_work/1/s/test/Microsoft.SqlTools.ServiceLayer.IntegrationTests/SchemaCompare/SchemaCompareServiceTests.cs:line 1899
   at Moq.It.<>c__DisplayClass3_0`1.<Is>b__0(TValue value)
   at Moq.MethodCall.Matches(Invocation invocation)
   at Moq.SetupCollection.FindMatchFor(Invocation invocation)
   at Moq.FindAndExecuteMatchingSetup.Handle(Invocation invocation, Mock mock)
   at Moq.Mock.Moq.IInterceptor.Intercept(Invocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.RequestContext`1Proxy_52.SendResult(SchemaCompareResult resultDetails)
   at Microsoft.SqlTools.ServiceLayer.SchemaCompare.SchemaCompareService.<>c__DisplayClass9_1.<<HandleSchemaCompareRequest>b__0>d.MoveNext() in /mnt/vss/_work/1/s/src/Microsoft.SqlTools.ServiceLayer/SchemaCompare/SchemaCompareService.cs:line 92
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.SqlTools.ServiceLayer.SchemaCompare.SchemaCompareService.<>c__DisplayClass9_1.<HandleSchemaCompareRequest>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()

```

**Comment by kisantia** [comment]
@ssreerama can you take a look at this since you've been making some changes here lately?

**Comment by ssreerama** [comment]
@lewis-sanchez , Is this test failing all the time or just a transient? I verified in my local and it is passing!

**Comment by lewis-sanchez** [comment]
@ssreerama, looking at the build history, it failed on Tuesday for build `#20220622.4`, then it passed for build `#20220622.5` and `#20220622.6`. Then it failed again yesterday for build `#20220623.1`. Since the failure isn't happening consistently and you weren't able to repro, I'd say it's transient.

**Comment by ssreerama** [comment]
True, verified the latest few builds and this test passes on all! Closing this issue :)
